#ifndef READER_EVIC_H
#define READER_EVIC_H
/**********************************************************************
* Includes
**********************************************************************/
#include "hal_defs.h"
/**********************************************************************
* Preprocessor Constants
**********************************************************************/

/**********************************************************************
* Typedefs
**********************************************************************/
typedef enum{
     EVIC_CHANNEL_CORE_TIMER                       = 0,
     EVIC_CHANNEL_CORE_SOFTWARE_0                  = 1,
     EVIC_CHANNEL_CORE_SOFTWARE_1                  = 2,
     EVIC_CHANNEL_EXTERNAL_0                       = 3,
     EVIC_CHANNEL_TIMER_1                          = 4,
     EVIC_CHANNEL_INPUT_CAPTURE_1_ERROR            = 5,
     EVIC_CHANNEL_INPUT_CAPTURE_1                  = 6,
     EVIC_CHANNEL_OUTPUT_COMPARE_1                 = 7,
     EVIC_CHANNEL_EXTERNAL_1                       = 8,
     EVIC_CHANNEL_TIMER_2                          = 9,
     EVIC_CHANNEL_INPUT_CAPTURE_2_ERROR            = 10,
     EVIC_CHANNEL_INPUT_CAPTURE_2                  = 11,
     EVIC_CHANNEL_OUTPUT_COMPARE_2                 = 12,
     EVIC_CHANNEL_EXTERNAL_2                       = 13,
     EVIC_CHANNEL_TIMER_3                          = 14,
     EVIC_CHANNEL_INPUT_CAPTURE_3_ERROR            = 15,
     EVIC_CHANNEL_INPUT_CAPTURE_3                  = 16,
     EVIC_CHANNEL_OUTPUT_COMPARE_3                 = 17,
     EVIC_CHANNEL_EXTERNAL_3                       = 18,
     EVIC_CHANNEL_TIMER_4                          = 19,
     EVIC_CHANNEL_INPUT_CAPTURE_4_ERROR            = 20,
     EVIC_CHANNEL_INPUT_CAPTURE_4                  = 21,
     EVIC_CHANNEL_OUTPUT_COMPARE_4                 = 22,
     EVIC_CHANNEL_EXTERNAL_4                       = 23,
     EVIC_CHANNEL_TIMER_5                          = 24,
     EVIC_CHANNEL_INPUT_CAPTURE_5_ERROR            = 25,
     EVIC_CHANNEL_INPUT_CAPTURE_5                  = 26,
     EVIC_CHANNEL_OUTPUT_COMPARE_5                 = 27,
     EVIC_CHANNEL_TIMER_6                          = 28,
     EVIC_CHANNEL_INPUT_CAPTURE_6_ERROR            = 29,
     EVIC_CHANNEL_INPUT_CAPTURE_6                  = 30,
     EVIC_CHANNEL_OUTPUT_COMPARE_6                 = 31,
     EVIC_CHANNEL_TIMER_7                          = 32,
     EVIC_CHANNEL_INPUT_CAPTURE_7_ERROR            = 33,
     EVIC_CHANNEL_INPUT_CAPTURE_7                  = 34,
     EVIC_CHANNEL_OUTPUT_COMPARE_7                 = 35,
     EVIC_CHANNEL_TIMER_8                          = 36,
     EVIC_CHANNEL_INPUT_CAPTURE_8_ERROR            = 37,
     EVIC_CHANNEL_INPUT_CAPTURE_8                  = 38,
     EVIC_CHANNEL_OUTPUT_COMPARE_8                 = 39,
     EVIC_CHANNEL_TIMER_9                          = 40,
     EVIC_CHANNEL_INPUT_CAPTURE_9_ERROR            = 41,
     EVIC_CHANNEL_INPUT_CAPTURE_9                  = 42,
     EVIC_CHANNEL_OUTPUT_COMPARE_9                 = 43,
     EVIC_CHANNEL_ADC                              = 44,
     EVIC_CHANNEL_ADC_FIFO                         = 45,
     EVIC_CHANNEL_ADC_DC1                          = 46,
     EVIC_CHANNEL_ADC_DC2                          = 47,
     EVIC_CHANNEL_ADC_DC3                          = 48,
     EVIC_CHANNEL_ADC_DC4                          = 49,
     EVIC_CHANNEL_ADC_DC5                          = 50,
     EVIC_CHANNEL_ADC_DC6                          = 51,
     EVIC_CHANNEL_ADC_DF1                          = 52,
     EVIC_CHANNEL_ADC_DF2                          = 53,
     EVIC_CHANNEL_ADC_DF3                          = 54,
     EVIC_CHANNEL_ADC_DF4                          = 55,
     EVIC_CHANNEL_ADC_DF5                          = 56,
     EVIC_CHANNEL_ADC_DF6                          = 57,
     EVIC_CHANNEL_ADC_FAULT                        = 58,
     EVIC_CHANNEL_ADC_DATA0                        = 59,
     EVIC_CHANNEL_ADC_DATA1                        = 60,
     EVIC_CHANNEL_ADC_DATA2                        = 61,
     EVIC_CHANNEL_ADC_DATA3                        = 62,
     EVIC_CHANNEL_ADC_DATA4                        = 63,
     EVIC_CHANNEL_ADC_DATA5                        = 64,
     EVIC_CHANNEL_ADC_DATA6                        = 65,
     EVIC_CHANNEL_ADC_DATA7                        = 66,
     EVIC_CHANNEL_ADC_DATA8                        = 67,
     EVIC_CHANNEL_ADC_DATA9                        = 68,
     EVIC_CHANNEL_ADC_DATA10                       = 69,
     EVIC_CHANNEL_ADC_DATA11                       = 70,
     EVIC_CHANNEL_ADC_DATA12                       = 71,
     EVIC_CHANNEL_ADC_DATA13                       = 72,
     EVIC_CHANNEL_ADC_DATA14                       = 73,
     EVIC_CHANNEL_ADC_DATA15                       = 74,
     EVIC_CHANNEL_ADC_DATA16                       = 75,
     EVIC_CHANNEL_ADC_DATA17                       = 76,
     EVIC_CHANNEL_ADC_DATA18                       = 77,
     EVIC_CHANNEL_ADC_DATA19                       = 78,
     EVIC_CHANNEL_ADC_DATA20                       = 79,
     EVIC_CHANNEL_ADC_DATA21                       = 80,
     EVIC_CHANNEL_ADC_DATA22                       = 81,
     EVIC_CHANNEL_ADC_DATA23                       = 82,
     EVIC_CHANNEL_ADC_DATA24                       = 83,
     EVIC_CHANNEL_ADC_DATA25                       = 84,
     EVIC_CHANNEL_ADC_DATA26                       = 85,
     EVIC_CHANNEL_ADC_DATA27                       = 86,
     EVIC_CHANNEL_ADC_DATA28                       = 87,
     EVIC_CHANNEL_ADC_DATA29                       = 88,
     EVIC_CHANNEL_ADC_DATA30                       = 89,
     EVIC_CHANNEL_ADC_DATA31                       = 90,
     EVIC_CHANNEL_ADC_DATA32                       = 91,
     EVIC_CHANNEL_ADC_DATA33                       = 92,
     EVIC_CHANNEL_ADC_DATA34                       = 93,
     EVIC_CHANNEL_ADC_DATA35                       = 94,
     EVIC_CHANNEL_ADC_DATA36                       = 95,
     EVIC_CHANNEL_ADC_DATA37                       = 96,
     EVIC_CHANNEL_ADC_DATA38                       = 97,
     EVIC_CHANNEL_ADC_DATA39                       = 98,
     EVIC_CHANNEL_ADC_DATA40                       = 99,
     EVIC_CHANNEL_ADC_DATA41                       = 100,
     EVIC_CHANNEL_ADC_DATA42                       = 101,
     EVIC_CHANNEL_ADC_DATA43                       = 102,
     EVIC_CHANNEL_ADC_DATA44                       = 103,
     EVIC_CHANNEL_CORE_PERF_COUNT                  = 104,
     EVIC_CHANNEL_CORE_FAST_DEBUG_CHAN             = 105,
     EVIC_CHANNEL_SYSTEM_BUS_PROTECTION            = 106,
     EVIC_CHANNEL_CRYPTO                           = 107,
     EVIC_CHANNEL_SPI1_FAULT                       = 109,
     EVIC_CHANNEL_SPI1_RX                          = 110,
     EVIC_CHANNEL_SPI1_TX                          = 111,
     EVIC_CHANNEL_UART1_FAULT                      = 112,
     EVIC_CHANNEL_UART1_RX                         = 113,
     EVIC_CHANNEL_UART1_TX                         = 114,
     EVIC_CHANNEL_I2C1_BUS                         = 115,
     EVIC_CHANNEL_I2C1_SLAVE                       = 116,
     EVIC_CHANNEL_I2C1_MASTER                      = 117,
     EVIC_CHANNEL_CHANGE_NOTICE_A                  = 118,
     EVIC_CHANNEL_CHANGE_NOTICE_B                  = 119,
     EVIC_CHANNEL_CHANGE_NOTICE_C                  = 120,
     EVIC_CHANNEL_CHANGE_NOTICE_D                  = 121,
     EVIC_CHANNEL_CHANGE_NOTICE_E                  = 122,
     EVIC_CHANNEL_CHANGE_NOTICE_F                  = 123,
     EVIC_CHANNEL_CHANGE_NOTICE_G                  = 124,
     EVIC_CHANNEL_PMP                              = 128,
     EVIC_CHANNEL_PMP_ERROR                        = 129,
     EVIC_CHANNEL_COMPARATOR_1                     = 130,
     EVIC_CHANNEL_COMPARATOR_2                     = 131,
     EVIC_CHANNEL_USB                              = 132,
     EVIC_CHANNEL_USB_DMA                          = 133,
     EVIC_CHANNEL_DMA0                             = 134,
     EVIC_CHANNEL_DMA1                             = 135,
     EVIC_CHANNEL_DMA2                             = 136,
     EVIC_CHANNEL_DMA3                             = 137,
     EVIC_CHANNEL_DMA4                             = 138,
     EVIC_CHANNEL_DMA5                             = 139,
     EVIC_CHANNEL_DMA6                             = 140,
     EVIC_CHANNEL_DMA7                             = 141,
     EVIC_CHANNEL_SPI2_FAULT                       = 142,
     EVIC_CHANNEL_SPI2_RX                          = 143,
     EVIC_CHANNEL_SPI2_TX                          = 144,
     EVIC_CHANNEL_UART2_FAULT                      = 145,
     EVIC_CHANNEL_UART2_RX                         = 146,
     EVIC_CHANNEL_UART2_TX                         = 147,
     EVIC_CHANNEL_I2C2_BUS                         = 148,
     EVIC_CHANNEL_I2C2_SLAVE                       = 149,
     EVIC_CHANNEL_I2C2_MASTER                      = 150,
     EVIC_CHANNEL_CAN1                             = 151,
     EVIC_CHANNEL_CAN2                             = 152,
     EVIC_CHANNEL_ETHERNET                         = 153,
     EVIC_CHANNEL_SPI3_FAULT                       = 154,
     EVIC_CHANNEL_SPI3_RX                          = 155,
     EVIC_CHANNEL_SPI3_TX                          = 156,
     EVIC_CHANNEL_UART3_FAULT                      = 157,
     EVIC_CHANNEL_UART3_RX                         = 158,
     EVIC_CHANNEL_UART3_TX                         = 159,
     EVIC_CHANNEL_I2C3_BUS                         = 160,
     EVIC_CHANNEL_I2C3_SLAVE                       = 161,
     EVIC_CHANNEL_I2C3_MASTER                      = 162,
     EVIC_CHANNEL_SPI4_FAULT                       = 163,
     EVIC_CHANNEL_SPI4_RX                          = 164,
     EVIC_CHANNEL_SPI4_TX                          = 165,
     EVIC_CHANNEL_RTCC                             = 166,
     EVIC_CHANNEL_FLASH_CONTROL                    = 167,
     EVIC_CHANNEL_PREFETCH                         = 168,
     EVIC_CHANNEL_SQI1                             = 169,
     EVIC_CHANNEL_UART4_FAULT                      = 170,
     EVIC_CHANNEL_UART4_RX                         = 171,
     EVIC_CHANNEL_UART4_TX                         = 172,
     EVIC_CHANNEL_I2C4_BUS                         = 173,
     EVIC_CHANNEL_I2C4_SLAVE                       = 174,
     EVIC_CHANNEL_I2C4_MASTER                      = 175,
     EVIC_CHANNEL_SPI5_FAULT                       = 176,
     EVIC_CHANNEL_SPI5_RX                          = 177,
     EVIC_CHANNEL_SPI5_TX                          = 178,
     EVIC_CHANNEL_UART5_FAULT                      = 179,
     EVIC_CHANNEL_UART5_RX                         = 180,
     EVIC_CHANNEL_UART5_TX                         = 181,
     EVIC_CHANNEL_I2C5_BUS                         = 182,
     EVIC_CHANNEL_I2C5_SLAVE                       = 183,
     EVIC_CHANNEL_I2C5_MASTER                      = 184,
     EVIC_CHANNEL_SPI6_FAULT                       = 185,
     EVIC_CHANNEL_SPI6_RX                          = 186,
     EVIC_CHANNEL_SPI6_TX                          = 187,
     EVIC_CHANNEL_UART6_FAULT                      = 188,
     EVIC_CHANNEL_UART6_RX                         = 189,
     EVIC_CHANNEL_UART6_TX                         = 190,
     EVIC_CHANNEL_ADC_EOS                          = 192,
     EVIC_CHANNEL_ADC_ARDY                         = 193,
     EVIC_CHANNEL_ADC_URDY                         = 194,
     EVIC_CHANNEL_ADC_EARLY                        = 196,
     EVIC_CHANNEL_ADC0_EARLY                       = 198,
     EVIC_CHANNEL_ADC1_EARLY                       = 199,
     EVIC_CHANNEL_ADC2_EARLY                       = 200,
     EVIC_CHANNEL_ADC3_EARLY                       = 201,
     EVIC_CHANNEL_ADC4_EARLY                       = 202,
     EVIC_CHANNEL_ADC7_EARLY                       = 205,
     EVIC_CHANNEL_ADC0_WARM                        = 206,
     EVIC_CHANNEL_ADC1_WARM                        = 207,
     EVIC_CHANNEL_ADC2_WARM                        = 208,
     EVIC_CHANNEL_ADC3_WARM                        = 209,
     EVIC_CHANNEL_ADC4_WARM                        = 210,
     EVIC_CHANNEL_ADC7_WARM                        = 213,
}EVIC_CHANNEL;
typedef enum{
    EVIC_STATE_ENABLED = 0,
    EVIC_STATE_DISABLED
}EVIC_STATE;
typedef enum{
    EVIC_PRIORITY_0 = 0,
    EVIC_PRIORITY_1    ,
    EVIC_PRIORITY_2    ,
    EVIC_PRIORITY_3    ,
    EVIC_PRIORITY_4    ,
    EVIC_PRIORITY_5    ,
    EVIC_PRIORITY_6    ,
    EVIC_PRIORITY_7    ,

}EVIC_PRIORITY;
typedef enum{
    EVIC_SUB_PRIORITY_0 = 0,
    EVIC_SUB_PRIORITY_1,
    EVIC_SUB_PRIORITY_2,
    EVIC_SUB_PRIORITY_3,
}EVIC_SUB_PRIORITY;
/**********************************************************************
* Function Prototypes
**********************************************************************/
#ifdef __cplusplus
extern "C"{
#endif
int         EVIC_init(void *data);
int         EVIC_channel_state_Set(
                EVIC_CHANNEL channel,
                EVIC_STATE state,
                EVIC_PRIORITY priority,
                EVIC_SUB_PRIORITY sub_priority
            );
void        EVIC_channel_priority(EVIC_CHANNEL channel, EVIC_PRIORITY, EVIC_SUB_PRIORITY);
void        EVIC_channel_set(EVIC_CHANNEL channel);
void        EVIC_channel_clr(EVIC_CHANNEL channel);
bool        EVIC_channel_pending_get(EVIC_CHANNEL channel);
void        EVIC_channel_pending_clear(EVIC_CHANNEL);
uint32_t    EVIC_enable_interrupts( void );
uint32_t    EVIC_disable_interrupts( void );
void        EVIC_restore_interrupts( uint32_t status );
#ifdef __cplusplus
}
#endif
#endif //READER_EVIC_H
