//
// Created by bleppe on 16/05/23.
//

#include "TestStateMachine.h"

StateEventSignal TestStateMachine::signals[10] = {
        [CONTROL_TYPE_INVALID] = EVENT_SIGNAL_INVALID,
        [CONTROL_TYPE_ENTER] = EVENT_SIGNAL_SELECT,
        [CONTROL_TYPE_RETURN] = EVENT_SIGNAL_RETURN,
        [CONTROL_TYPE_CANCEL] = EVENT_SIGNAL_CANCEL,
        [CONTROL_TYPE_OPTION] = EVENT_SIGNAL_OPTION,
        [CONTROL_TYPE_UP] = EVENT_SIGNAL_INVALID,
        [CONTROL_TYPE_DOWN] = EVENT_SIGNAL_INVALID,
        [CONTROL_TYPE_PUMP] = EVENT_SIGNAL_PUMP,
        [CONTROL_TYPE_SPACE] = EVENT_SIGNAL_INVALID,
        [CONTROL_TYPE_TICK] = EVENT_SIGNAL_TICK,
};